import type { TickerConfig } from '../types';

export const TICKERS: TickerConfig[] = [
  // ── Space / Defense ──────────────────────────────────────────────────────
  {
    ticker: 'RKLB',
    name: 'Rocket Lab',
    sectors: ['space', 'defense'],
    color: '#00c8ff',
    description: 'End-to-end space company; Electron launch vehicle and Neutron in development',
    fiscalYearEnd: 'December',
  },
  {
    ticker: 'PL',
    name: 'Planet Labs',
    sectors: ['space', 'defense'],
    color: '#a259ff',
    description: 'Daily Earth-imaging satellite constellation; defense and commercial data analytics',
    fiscalYearEnd: 'January',
  },
  {
    ticker: 'RDW',
    name: 'Redwire',
    sectors: ['space', 'defense'],
    color: '#ff6b35',
    description: 'Space infrastructure manufacturer; solar arrays, structures, and payloads',
    fiscalYearEnd: 'December',
  },
  // ── Clean Energy / AI Infra ───────────────────────────────────────────────
  {
    ticker: 'VST',
    name: 'Vistra Energy',
    sectors: ['clean_energy', 'ai_infrastructure'],
    description: 'Largest competitive power generator in the US; nuclear and natural gas fleet',
    fiscalYearEnd: 'December',
  },
  {
    ticker: 'IREN',
    name: 'Iris Energy',
    sectors: ['ai_infrastructure', 'clean_energy'],
    description: 'Bitcoin miner and AI cloud compute operator; renewable-powered data centers',
    fiscalYearEnd: 'June',
  },
  {
    ticker: 'CRWV',
    name: 'CoreWeave',
    sectors: ['ai_infrastructure'],
    description: 'GPU-accelerated cloud infrastructure for AI workloads; Nvidia-backed',
    fiscalYearEnd: 'December',
  },
  {
    ticker: 'CEG',
    name: 'Constellation Energy',
    sectors: ['clean_energy', 'ai_infrastructure'],
    description: 'Largest US nuclear operator; clean power for data centers and AI',
    fiscalYearEnd: 'December',
  },
  {
    ticker: 'BWXT',
    name: 'BWX Technologies',
    sectors: ['clean_energy', 'defense'],
    description: 'Nuclear components and services for defense and commercial power; SMR developer',
    fiscalYearEnd: 'December',
  },
  // ── AI Infrastructure ──────────────────────────────────────────────────────
  {
    ticker: 'NVDA',
    name: 'Nvidia',
    sectors: ['ai_infrastructure'],
    description: 'GPU leader for AI training and inference; CUDA ecosystem dominance',
    fiscalYearEnd: 'January',
  },
  {
    ticker: 'PLTR',
    name: 'Palantir',
    sectors: ['ai_infrastructure', 'defense'],
    description: 'AI and data analytics platform for defense and commercial enterprise',
    fiscalYearEnd: 'December',
  },

  // ── Space Economy (continued) ─────────────────────────────────────────────
  {
    ticker: 'LUNR',
    name: 'Intuitive Machines',
    sectors: ['space', 'defense'],
    description: 'Lunar delivery and surface operations services; NASA prime contractor',
    fiscalYearEnd: 'December',
    nextEarningsDate: null,
    specialNotes: 'Only commercial company to successfully land on the Moon',
  },
  {
    ticker: 'ASTS',
    name: 'AST SpaceMobile',
    sectors: ['space', 'ai_infrastructure'],
    description: 'Building direct-to-smartphone satellite broadband constellation',
    fiscalYearEnd: 'December',
    nextEarningsDate: null,
    specialNotes: 'BlueBird constellation; AT&T and Verizon commercial agreements',
  },
  {
    ticker: 'SPIR',
    name: 'Spire Global',
    sectors: ['space', 'ai_infrastructure'],
    description: 'Data-as-a-service from satellites: weather, maritime, aviation analytics',
    fiscalYearEnd: 'December',
    nextEarningsDate: null,
    specialNotes: null,
  },
  {
    ticker: 'BKSY',
    name: 'BlackSky Technology',
    sectors: ['space', 'defense'],
    description: 'High-frequency Earth observation constellation; defense and intelligence focus',
    fiscalYearEnd: 'December',
    nextEarningsDate: null,
    specialNotes: null,
  },

  // ── AI Data Center Infrastructure ─────────────────────────────────────────
  {
    ticker: 'CORZ',
    name: 'Core Scientific',
    sectors: ['ai_infrastructure'],
    description: 'Bitcoin miner pivoting to HPC/AI hosting; 12-year $10.2B CoreWeave contract',
    fiscalYearEnd: 'December',
    nextEarningsDate: null,
    specialNotes: 'CoreWeave take-or-pay structure funds nearly all CapEx',
  },
  {
    ticker: 'WULF',
    name: 'TeraWulf',
    sectors: ['ai_infrastructure', 'clean_energy'],
    description: 'Nuclear-powered HPC and AI data center operator; zero-carbon compute focus',
    fiscalYearEnd: 'December',
    nextEarningsDate: null,
    specialNotes: 'Lake Mariner facility powered by nuclear — structural cost advantage',
  },
  {
    ticker: 'HUT',
    name: 'Hut 8',
    sectors: ['ai_infrastructure'],
    description: 'Bitcoin miner transitioning to AI/HPC managed services and colocation',
    fiscalYearEnd: 'December',
    nextEarningsDate: null,
    specialNotes: null,
  },
  {
    ticker: 'APLD',
    name: 'Applied Digital',
    sectors: ['ai_infrastructure'],
    description: 'HPC data center builder and operator targeting AI workloads',
    fiscalYearEnd: 'May',
    nextEarningsDate: null,
    specialNotes: null,
  },
  {
    ticker: 'AMD',
    name: 'Advanced Micro Devices',
    sectors: ['ai_infrastructure'],
    description: 'Semiconductor company; MI300X GPU series competing with Nvidia for AI training',
    fiscalYearEnd: 'December',
    nextEarningsDate: null,
    specialNotes: 'MI300X gaining share in inference workloads',
  },
  {
    ticker: 'AVGO',
    name: 'Broadcom',
    sectors: ['ai_infrastructure'],
    description: 'Semiconductor and infrastructure software; custom AI chip (XPU) leader',
    fiscalYearEnd: 'October',
    nextEarningsDate: null,
    specialNotes: 'Custom AI silicon for Google, Meta, Apple — $60–90B AI revenue TAM by 2027',
  },

  // ── Clean Energy & Nuclear ────────────────────────────────────────────────
  {
    ticker: 'CCJ',
    name: 'Cameco',
    sectors: ['clean_energy'],
    description: "World's largest publicly traded uranium producer; 15% of global supply",
    fiscalYearEnd: 'December',
    nextEarningsDate: null,
    specialNotes: null,
  },
  {
    ticker: 'LEU',
    name: 'Centrus Energy',
    sectors: ['clean_energy', 'defense'],
    description: 'US uranium enrichment; HALEU production for advanced reactors and SMRs',
    fiscalYearEnd: 'December',
    nextEarningsDate: null,
    specialNotes: '$900M DOE contract for HALEU enrichment expansion',
  },
  {
    ticker: 'TLN',
    name: 'Talen Energy',
    sectors: ['clean_energy', 'ai_infrastructure'],
    description: 'Nuclear power operator; Susquehanna plant data center co-location deals',
    fiscalYearEnd: 'December',
    nextEarningsDate: null,
    specialNotes: 'Amazon co-location deal at nuclear plant — early mover in nuclear-powered compute',
  },
  {
    ticker: 'OKLO',
    name: 'Oklo',
    sectors: ['clean_energy', 'ai_infrastructure'],
    description: 'Advanced fission company building microreactors for data centers and defense',
    fiscalYearEnd: 'December',
    nextEarningsDate: null,
    specialNotes: 'Pre-revenue; Meta partnership for Ohio data center power; Sam Altman chairman',
  },

  // ── LNG Export ────────────────────────────────────────────────────────────
  {
    ticker: 'LNG',
    name: 'Cheniere Energy',
    sectors: ['lng_export'],
    description: 'Largest US LNG exporter; Sabine Pass and Corpus Christi liquefaction terminals',
    fiscalYearEnd: 'December',
    nextEarningsDate: null,
    specialNotes: 'Long-term take-or-pay contracts; ~90% revenue contracted',
  },
  {
    ticker: 'VG',
    name: 'Venture Global',
    sectors: ['lng_export'],
    description: 'Newest US LNG exporter; Calcasieu Pass operational, CP2 under development',
    fiscalYearEnd: 'December',
    nextEarningsDate: null,
    specialNotes: 'Recently IPO\'d; significant contract disputes with European buyers — key risk',
  },
  {
    ticker: 'CQP',
    name: 'Cheniere Energy Partners',
    sectors: ['lng_export'],
    description: 'MLP holding Sabine Pass LNG facility; high distribution yield play on LNG',
    fiscalYearEnd: 'December',
    nextEarningsDate: null,
    specialNotes: 'More yield-focused than LNG parent; lower growth, higher current income',
  },

  // ── Defense ───────────────────────────────────────────────────────────────
  {
    ticker: 'KTOS',
    name: 'Kratos Defense',
    sectors: ['defense', 'ai_infrastructure'],
    description: 'Unmanned systems, satellites, and high-performance electronics for US military',
    fiscalYearEnd: 'December',
    nextEarningsDate: null,
    specialNotes: 'Drone and hypersonics programs; HASTE competitor to RKLB',
  },
  {
    ticker: 'LDOS',
    name: 'Leidos',
    sectors: ['defense', 'ai_infrastructure'],
    description: 'Defense IT integrator; government AI systems, satellite ground infrastructure',
    fiscalYearEnd: 'December',
    nextEarningsDate: null,
    specialNotes: 'Processes satellite data for US intelligence community',
  },
  {
    ticker: 'BAH',
    name: 'Booz Allen Hamilton',
    sectors: ['defense', 'ai_infrastructure'],
    description: 'Defense and government consulting; AI and data analytics for US agencies',
    fiscalYearEnd: 'March',
    nextEarningsDate: null,
    specialNotes: 'Major consumer of space-derived intelligence data; AI integration across DoD',
  },
];

export const TICKER_MAP = Object.fromEntries(
  TICKERS.map((t) => [t.ticker, t]),
) as Record<string, TickerConfig>;

export const ALL_TICKERS = TICKERS.map((t) => t.ticker);
